import os
import re
import datetime
from pathlib import Path
from core.database import SessionLocal, Entity, Observation


def _safe_filename(identifier: str) -> str:
    return re.sub(r'[^A-Za-z0-9_.-]', '_', identifier)


def generate_dossier(identifier: str) -> str:
    """Generates a Markdown dossier for a specific entity."""
    session = SessionLocal()
    try:
        entity = session.query(Entity).filter_by(value=identifier).first()
        if not entity:
            return f"Error: No records found for '{identifier}' in the local enclave."

        observations = session.query(Observation).filter_by(entity_id=entity.id).all()

        now = datetime.datetime.now(datetime.timezone.utc)

        lines = [
            f"# XGhostSignal Intelligence Dossier",
            f"**Generated:** {now.isoformat()}",
            f"**Classification:** LOCAL ONLY (TLP:RED)",
            "---",
            f"## Target Summary",
            f"- **Identifier:** `{entity.value}`",
            f"- **Normalized:** `{entity.normalized_value}`",
            f"- **Type:** `{entity.type}`",
            f"- **First Sighted:** {entity.created_at}",
            f"- **Primary Source:** {entity.source}",
            "",
            f"## Geospatial & Contextual Observations",
            f"Total recorded sightings: {len(observations)}",
            ""
        ]

        if not observations:
            lines.append("> No geospatial or contextual observations recorded for this entity.")
        else:
            for obs in observations:
                lines.append(f"### Observation [{obs.timestamp}]")
                lines.append(f"- **Type:** {obs.observation_type}")
                if obs.latitude is not None and obs.longitude is not None:
                    lines.append(f"- **Coordinates:** {obs.latitude}, {obs.longitude}")
                if obs.region_name:
                    lines.append(f"- **Region:** {obs.region_name}")
                lines.append(f"- **Confidence:** {obs.confidence}")
                lines.append(f"- **Source:** {obs.source}")
                lines.append("")

        lines.append("---")
        lines.append("*Report generated by XGhostSignal Evidence Vault.*")

        report_text = "\n".join(lines)

        reports_dir = Path("reports")
        reports_dir.mkdir(exist_ok=True)
        safe_id = _safe_filename(identifier)
        filename = reports_dir / f"dossier_{safe_id}_{int(now.timestamp())}.md"
        filename.write_text(report_text, encoding="utf-8")

        return str(filename)
    finally:
        session.close()
