import os
import datetime
from core.database import SessionLocal, Entity, Observation

def generate_dossier(identifier: str) -> str:
    """Generates a Markdown dossier for a specific entity."""
    session = SessionLocal()
    try:
        entity = session.query(Entity).filter_by(value=identifier).first()
        if not entity:
            return f"Error: No records found for '{identifier}' in the local enclave."

        observations = session.query(Observation).filter_by(entity_id=entity.id).all()
        
        # Build Markdown
        lines = [
            f"# XGhostSignal Intelligence Dossier",
            f"**Generated:** {datetime.datetime.utcnow().isoformat()}Z",
            f"**Classification:** LOCAL ONLY (TLP:RED)",
            "---",
            f"## Target Summary",
            f"- **Identifier:** `{entity.value}`",
            f"- **Normalized:** `{entity.normalized_value}`",
            f"- **Type:** `{entity.type}`",
            f"- **First Sighted:** {entity.created_at}",
            f"- **Primary Source:** {entity.source}",
            "",
            f"## Geospatial & Contextual Observations",
            f"Total recorded sightings: {len(observations)}",
            ""
        ]

        if not observations:
            lines.append("> No geospatial or contextual observations recorded for this entity.")
        else:
            for obs in observations:
                lines.append(f"### Observation [{obs.timestamp}]")
                lines.append(f"- **Type:** {obs.observation_type}")
                if obs.latitude and obs.longitude:
                    lines.append(f"- **Coordinates:** {obs.latitude}, {obs.longitude}")
                if obs.region_name:
                    lines.append(f"- **Region:** {obs.region_name}")
                lines.append(f"- **Confidence:** {obs.confidence}")
                lines.append(f"- **Source:** {obs.source}")
                lines.append("")

        lines.append("---")
        lines.append("*Report generated by XGhostSignal Evidence Vault.*")
        
        report_text = "\n".join(lines)
        
        # Save to disk
        os.makedirs("reports", exist_ok=True)
        safe_id = identifier.replace("+", "").replace(" ", "_")
        filename = f"reports/dossier_{safe_id}_{int(datetime.datetime.utcnow().timestamp())}.md"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(report_text)
            
        return filename
    finally:
        session.close()
